### ISSUE TITLE
Print Date Error

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#64]
When updating a job, I keep getting an error message as attached. It seems like on the updated, something breaks regarding the PrintDate/DueDate connection. I am not updating anything regarding the date, but it won't let me save the job because of the error. I can't adjust the Print date from the edit job page, so it basically kills the update. Thoughts?
![picture 3](https://f.cloud.github.com/assets/3011006/519832/db4135b0-bf22-11e2-862c-9071dabda7bd.png)

**Comment by kPOWz** [comment]
I've been trying to recreate this one , but just haven't had any luck making the error - they're updating fine for me!

Ben, I should have a much better shot of finding what's going on with this one more quickly if you give some more specific steps to recreate the problem - in this case the job id should do!

**Comment by kPOWz** [comment]
Figured this one out and have a fix for it!

This happens when there is bad, old data that violates our newly enforced rule of no print dates that are greater than due dates. 

To get around Gus's bad legacy data I've made it so when bad data on existing records is encountered the print date is made to match the due date before validation is kicked off.
