### ISSUE TITLE
Auto-save Job Form

### ISSUE THREAD

**Issue by johnsolarz** [kPOWz/Deviner#80]
Similar to a google doc "all changes saved in drive"

**Comment by kPOWz** [comment]
I've been thinking about this one @alliefayden & @johnsolarz.  I think the way to do it - instead of saving the job immediately on each/any change - is to collect changes and save them every 5 or 10 seconds.

If a user tries to exit the page when unsaved changes are queued, she'll be asked to cancel or save the changes explicitly in a prompt.

**Comment by kPOWz** [comment]
After some study, looks like this workflow will only jive with /update , not brand new jobs. 

This is because after we initially save a job, GUS redirect the user to /update/job#. is would be really annoying if after 30 seconds of filling in a new job you got interrupted with a redirect.

**Comment by benjanders** [comment]
I think auto saving for /update only is a good idea.
